In [10]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
type(L[0])

int

In [12]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [14]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
import numpy as np
np.array([1,4,2,5,3])


array([1, 4, 2, 5, 3])

In [16]:
np.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [17]:
np.array([1,2,3,4], dtype="float32")

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [18]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [19]:
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones((3,5), dtype = 'float')

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [21]:
np.full((3,5), 3.14, dtype=float)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [22]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [24]:
np.random.random((3,3))

array([[ 0.21561241,  0.07657735,  0.59832312],
       [ 0.8250188 ,  0.17859727,  0.82858583],
       [ 0.13638794,  0.66910357,  0.05360845]])

In [25]:
#Mean of 0 standard deviation of 1
np.random.normal(0, 1, (3,3))

array([[ 0.05095728, -0.76561165, -0.31890136],
       [ 0.35706134,  0.09288417,  0.33588559],
       [ 0.89138501, -0.63263878, -1.84418404]])

In [26]:
np.random.randint(0, 10, (3,3))

array([[2, 7, 7],
       [4, 3, 8],
       [2, 0, 6]])

In [27]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [28]:
np.empty(3)

array([ 1.,  1.,  1.])

In [29]:
np.zeros((3,3), dtype='int16')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [30]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

In [31]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 dtype:", x3.dtype)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes", x3.nbytes, "bytes")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int32
x3 itemsize: 4 bytes
x3 nbytes 240 bytes


In [32]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [34]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [35]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [36]:
#np.vstack
#np.hstack
#vsplit
#hsplit
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [37]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

values = np.random.randint(1, 10, size = 5)
compute_reciprocals(values)


array([ 0.16666667,  1.        ,  0.25      ,  0.25      ,  0.125     ])

In [39]:
big_array = np.random.randint(1, 100, size = 1000000)
%timeit compute_reciprocals(big_array)

1 loop, best of 3: 4.89 s per loop


In [40]:
print(compute_reciprocals(values))
print(1.0 / values)

[ 0.16666667  1.          0.25        0.25        0.125     ]
[ 0.16666667  1.          0.25        0.25        0.125     ]


In [41]:
%timeit (1.0 / big_array)

100 loops, best of 3: 5.39 ms per loop


In [42]:
np.arange(5) / np.arange(1,6)

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

In [43]:
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [44]:
x = np.arange(4)
print("x   =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) #floor division


x   = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]


In [45]:
print("-x   =",-x)
print("x ** 2 =", x**2)
print("x % 2 =", x % 2)

-x   = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In [46]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[  0.  10.  20.  30.  40.]


In [47]:
#Get an array of 10 zeros
y = np.zeros(10)
#take the value 2^x for every other value starting at index 0
np.power(2, x, out=y[::2])
print(y)

[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


In [48]:
x = np.arange(1,6)
#5 + 4 + 3 + 2 + 1 = 15
np.add.reduce(x)

15

In [49]:
np.multiply.reduce(x)

120

In [50]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [51]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [52]:
x = np.arange(1,6)

In [53]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [54]:
np.add.outer(x,x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [55]:
L = np.random.random(100)

In [56]:
sum(L)
np.sum(L)

50.461758453195642

In [57]:
min(big_array), max(big_array)

(1, 99)

In [58]:
np.min(big_array), np.max(big_array)

(1, 99)

In [59]:
M = np.random.random((3,4))
print(M)

[[ 0.49555108  0.9552979   0.81778172  0.49902653]
 [ 0.22465879  0.89005733  0.30654364  0.37441302]
 [ 0.75259926  0.17746194  0.10144419  0.9999925 ]]


In [60]:
M.sum()

6.5948279037180324

In [61]:
#Smallest of the columns
M.min(axis = 0)

array([ 0.22465879,  0.17746194,  0.10144419,  0.37441302])

In [62]:
#Biggest of the rows
M.max(axis = 1)

array([ 0.9552979 ,  0.89005733,  0.9999925 ])

In [63]:
!head -4 data/president_heights.csv

order,name,height(cm)
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189


In [65]:
import pandas as pd
data = pd.read_csv('data/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [66]:
print("Mean height:", heights.mean())
print("Standard Deviation:", heights.std())
print("Minimum height:", heights.min())
print("Maximum height:", heights.max())

Mean height: 179.738095238
Standard Deviation: 6.93184344275
Minimum height: 163
Maximum height: 193


In [67]:
print("25th percentile:", np.percentile(heights, 25))
print("Median:", np.median(heights))
print("75th percentile", np.percentile(heights, 75))

25th percentile: 174.25
Median: 182.0
75th percentile 183.0


In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn
seaborn.set()

plt