In [2]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L[0])

int

In [4]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [6]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np
np.array([1,4,2,5,3])


array([1, 4, 2, 5, 3])

In [9]:
np.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [10]:
np.array([1,2,3,4], dtype="float32")

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [11]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [12]:
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3,5), dtype = 'float')

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [15]:
np.full((3,5), 3.14, dtype=float)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [16]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [18]:
np.random.random((3,3))

array([[ 0.53398679,  0.36013129,  0.94161128],
       [ 0.50555148,  0.89430646,  0.03276184],
       [ 0.66670783,  0.05491195,  0.45835067]])

In [19]:
#Mean of 0 standard deviation of 1
np.random.normal(0, 1, (3,3))

array([[ 1.13770371, -0.38568494, -0.65522156],
       [-0.79407394, -0.1047418 , -0.6759753 ],
       [ 0.21720042, -1.25457618, -0.01017195]])

In [20]:
np.random.randint(0, 10, (3,3))

array([[2, 1, 7],
       [0, 6, 5],
       [7, 9, 9]])

In [21]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [22]:
np.empty(3)

array([ 1.,  1.,  1.])

In [23]:
np.zeros((3,3), dtype='int16')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [25]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

In [30]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 dtype:", x3.dtype)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes", x3.nbytes, "bytes")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int32
x3 itemsize: 4 bytes
x3 nbytes 240 bytes


In [32]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [34]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [35]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [36]:
#np.vstack
#np.hstack
#vsplit
#hsplit
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [37]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

values = np.random.randint(1, 10, size = 5)
compute_reciprocals(values)


array([ 0.16666667,  1.        ,  0.25      ,  0.25      ,  0.125     ])

In [39]:
big_array = np.random.randint(1, 100, size = 1000000)
%timeit compute_reciprocals(big_array)

4.2 s ± 218 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [40]:
print(compute_reciprocals(values))
print(1.0 / values)

[ 0.16666667  1.          0.25        0.25        0.125     ]
[ 0.16666667  1.          0.25        0.25        0.125     ]


In [41]:
%timeit (1.0 / big_array)

6.39 ms ± 433 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [43]:
np.arange(5) / np.arange(1,6)

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

In [44]:
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [45]:
x = np.arange(4)
print("x   =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) #floor division


x   = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]


In [46]:
print("-x   =",-x)
print("x ** 2 =", x**2)
print("x % 2 =", x % 2)

-x   = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In [51]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[  0.  10.  20.  30.  40.]


In [53]:
#Get an array of 10 zeros
y = np.zeros(10)
#take the value 2^x for every other value starting at index 0
np.power(2, x, out=y[::2])
print(y)

[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


In [54]:
x = np.arange(1,6)
#5 + 4 + 3 + 2 + 1 = 15
np.add.reduce(x)

15

In [56]:
np.multiply.reduce(x)

120

In [58]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [57]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)